# generated by datamodel-codegen:
#   filename:  openapi/powercontext.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    model_validator,
)


class ArtifactReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    revision: Annotated[StrictInt, Field(ge=1)]


class ScopeExternalReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    value: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]


class ContextReference(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ScopeDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    summary: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]
    parent_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    context_references: list[ContextReference]
    external_references: list[ScopeExternalReference]
    version: Annotated[StrictInt, Field(ge=1)]


class ScopePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[ScopeDescriptor]


class CreateScopeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    summary: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]
    parent_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    context_references: Annotated[list[ContextReference], Field(validate_default=True)] = []
    external_references: Annotated[list[ScopeExternalReference], Field(validate_default=True)] = []
    idempotency_key: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class GetScopeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class UpdateScopeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    summary: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]
    parent_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    context_references: Annotated[list[ContextReference], Field(validate_default=True)] = []
    external_references: Annotated[list[ScopeExternalReference], Field(validate_default=True)] = []


class SetDefaultScopeRequest(RootModel[GetScopeRequest]):
    root: GetScopeRequest


class ScopeSelectionMode(StrEnum):
    ALL = "all"
    EXACT = "exact"
    SUBTREE = "subtree"


class ScopeId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ScopeSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: ScopeSelectionMode
    scope_ids: Annotated[list[ScopeId], Field(validate_default=True)] = []
    root_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None


class ResolveScopeSelectionRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selection: ScopeSelection


class ScopeBindingKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    integration: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    kind: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern=".*\\S.*")]
    external_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ScopeBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: ScopeBindingKey
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class SetScopeBindingRequest(RootModel[ScopeBinding]):
    root: ScopeBinding


class ClearScopeBindingRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: ScopeBindingKey


class ClearScopeBindingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cleared: StrictBool


class ResolveScopeBindingRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    explicit_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    binding_keys: Annotated[list[ScopeBindingKey], Field(validate_default=True)] = []


class ApproveArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]


class FamilyCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    total: Annotated[StrictInt, Field(ge=0)]


class MemoryKindCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    total: Annotated[StrictInt, Field(ge=0)]
    active: Annotated[StrictInt, Field(ge=0)]
    inactive: Annotated[StrictInt, Field(ge=0)]


class SourceInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    memory_processed: Annotated[StrictInt, Field(ge=0)]
    memory_pending: Annotated[StrictInt, Field(ge=0)]


class ArtifactInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    by_family: list[FamilyCount]


class MemoryEntryInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    active: Annotated[StrictInt, Field(ge=0)]
    inactive: Annotated[StrictInt, Field(ge=0)]
    by_kind: list[MemoryKindCount]


class MemoryInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entries: MemoryEntryInventoryStatistics


class ModelUsageValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requests: Annotated[StrictInt, Field(ge=0)]
    input_tokens: Annotated[StrictInt | None, Field(ge=0)]
    output_tokens: Annotated[StrictInt | None, Field(ge=0)]


class ModelUsageStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    generation: ModelUsageValue
    embedding: ModelUsageValue


class ModelUsagePurposeBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    purpose: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    generation: ModelUsageValue
    embedding: ModelUsageValue


class ModelUsageDay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    generation: ModelUsageValue
    embedding: ModelUsageValue
    by_purpose: Annotated[list[ModelUsagePurposeBreakdown], Field(max_length=16)]


class Timezone(StrEnum):
    UTC = "UTC"


class TokenEstimatorProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    estimator_id: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    version: Annotated[StrictStr, Field(max_length=64, min_length=1)]


class RecallTokenValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    preparations: Annotated[StrictInt, Field(ge=0)]
    ready_preparations: Annotated[StrictInt, Field(ge=0)]
    comparable_preparations: Annotated[StrictInt, Field(ge=0)]
    baseline_tokens: Annotated[StrictInt, Field(ge=0)]
    recalled_tokens: Annotated[StrictInt, Field(ge=0)]
    token_reduction: StrictInt


class RecallTokenDay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    preparations: Annotated[StrictInt, Field(ge=0)]
    ready_preparations: Annotated[StrictInt, Field(ge=0)]
    comparable_preparations: Annotated[StrictInt, Field(ge=0)]
    baseline_tokens: Annotated[StrictInt, Field(ge=0)]
    recalled_tokens: Annotated[StrictInt, Field(ge=0)]
    token_reduction: StrictInt


class WorkClaimBasis(StrEnum):
    DECLARED = "declared"
    VERIFIED = "verified"


class Schema(StrEnum):
    POWERCONTEXT_WORK_CONTRACT_V1 = "powercontext.work-contract.v1"


class Trust(StrEnum):
    UNTRUSTED_INPUT = "untrusted_input"


class InScopeItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class Exclusion(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class CompletionCriterion(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class AuthorizationNote(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class OpenQuestion(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class Schema1(StrEnum):
    POWERCONTEXT_CURRENT_WORK_HANDOFF_V1 = "powercontext.current-work-handoff.v1"


class Omission(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class WorkSourceKind(StrEnum):
    WORK_CONTRACT = "work-contract"
    HANDOFF_BOUNDARY = "handoff-boundary"
    HANDOFF_RECEIPT = "handoff-receipt"
    TASK_OUTCOME = "task-outcome"


class HandoffReceiptStatus(StrEnum):
    ACCEPTED = "accepted"
    NEEDS_CLARIFICATION = "needs_clarification"
    DECLINED = "declined"


class HandoffAcknowledgementSelection(StrEnum):
    PREPARED = "prepared"
    EXACT = "exact"


class LiveStateCheckStatus(StrEnum):
    CONFIRMED = "confirmed"
    MISMATCH = "mismatch"
    NOT_CHECKED = "not_checked"


class ReceiverReadinessCheckStatus(StrEnum):
    CONFIRMED = "confirmed"
    INSUFFICIENT = "insufficient"
    NOT_CHECKED = "not_checked"


class ReceiverChecks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    live_state: LiveStateCheckStatus
    capability: ReceiverReadinessCheckStatus
    authorization: ReceiverReadinessCheckStatus


class TaskOutcomeStatus(StrEnum):
    SUCCEEDED = "succeeded"
    PARTIAL = "partial"
    BLOCKED = "blocked"
    FAILED = "failed"
    CANCELLED = "cancelled"
    UNKNOWN = "unknown"


class TaskCheckStatus(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"
    TIMED_OUT = "timed_out"
    UNAVAILABLE = "unavailable"
    CANCELLED = "cancelled"
    UNKNOWN = "unknown"


class Schema2(StrEnum):
    POWERCONTEXT_TASK_OUTCOME_V1 = "powercontext.task-outcome.v1"


class Trust2(StrEnum):
    UNTRUSTED_OBSERVATION = "untrusted_observation"


class RemainingWorkItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class CaptureContentSourceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    content: Annotated[StrictStr, Field(max_length=200000, min_length=1)]
    metadata: dict[str, Any] | None = None


class Kind(StrEnum):
    ARTIFACT = "artifact"


class HandoffArtifactCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["artifact"]
    artifact_ref: ArtifactReference


class Kind1(StrEnum):
    MEMORY = "memory"


class Trust3(StrEnum):
    UNTRUSTED_HISTORY = "untrusted_history"


class Kind2(StrEnum):
    SOURCE = "source"


class ExperienceProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    situation: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    action: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    outcome: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    lesson: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]


class SkillValidationItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern="^\\S(?:.*\\S)?$")]


class Provider(StrEnum):
    CODEX = "codex"
    CLAUDE_CODE = "claude_code"


class AgentKind(StrEnum):
    CODEX = "codex"
    CLAUDE_CODE = "claude_code"


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: StrictStr
    message: StrictStr
    details: Annotated[dict[str, Any] | None, Field(...)]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorDetail


class FlushMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class GetArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class GetExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact: ArtifactReference


class GetSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact: ArtifactReference


class ListHandoffReportProjectsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: StrictStr | None = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50
    include_archived: StrictBool = False


class GetHandoffReportProjectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class Label(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=128, min_length=1)]


class ListHandoffReportWorkstreamsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    cursor: StrictStr | None = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50
    include_archived: StrictBool = False


class ListHandoffReportKnownScopesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: StrictStr | None = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50


class KnownHandoffScope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class KnownHandoffScopePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[KnownHandoffScope]
    next_cursor: StrictStr | None = None


class HandoffReportPeriodRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: AwareDatetime
    end: AwareDatetime
    timezone: Annotated[StrictStr | None, Field(max_length=256, min_length=1)] = None
    compare_to_previous_period: StrictBool = False


class ReportActivitySource(StrEnum):
    HANDOFF_OBSERVATION = "handoff_observation"
    GIT_COMMIT = "git_commit"
    GIT_WORKTREE = "git_worktree"
    CODING_SESSION = "coding_session"
    OTHER = "other"


class ReportTimeBasis(StrEnum):
    SOURCE_REPORTED = "source_reported"
    HOST_OBSERVED = "host_observed"
    FIRST_SEEN = "first_seen"
    CURRENT_ONLY = "current_only"
    UNKNOWN = "unknown"


class HandoffReportActivityAgent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    provider: Annotated[StrictStr | None, Field(max_length=64, min_length=1)] = None
    label: Annotated[StrictStr | None, Field(max_length=128, min_length=1)] = None


class HandoffReportActivityVcsContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    branch: Annotated[StrictStr | None, Field(max_length=256, min_length=1)] = None
    head_revision: Annotated[StrictStr | None, Field(max_length=256, min_length=1)] = None


class Schema3(StrEnum):
    POWERCONTEXT_HANDOFF_REPORT_ACTIVITY_V1 = "powercontext.handoff-report-activity.v1"


class Trust4(StrEnum):
    UNTRUSTED_OBSERVATION = "untrusted_observation"


class ListHandoffReportActivitiesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    period_start: AwareDatetime | None = None
    period_end: AwareDatetime | None = None
    sources: Annotated[list[ReportActivitySource] | None, Field(max_length=5)] = None
    after_cursor: Annotated[StrictInt, Field(ge=0)] = 0
    through_cursor: Annotated[StrictInt | None, Field(ge=0)] = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50


class PurgeHandoffReportActivitiesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    observed_before: AwareDatetime


class PurgeHandoffReportActivitiesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deleted_count: Annotated[StrictInt, Field(ge=0)]


class Provider1(StrEnum):
    GITHUB = "github"
    GITLAB = "gitlab"
    LOCAL = "local"
    OTHER = "other"


class HandoffReportRepositoryRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    provider: Provider1
    repository_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1)]
    normalized_remote: Annotated[StrictStr | None, Field(max_length=2048, min_length=1)]
    subpath: Annotated[StrictStr | None, Field(max_length=1024, min_length=1)]


class Schema4(StrEnum):
    POWERCONTEXT_WORKSPACE_BINDING_V1 = "powercontext.workspace-binding.v1"


class State(StrEnum):
    CONFIRMED = "confirmed"
    DETACHED = "detached"


class HandoffReportWorkspaceBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema4, Field(alias="schema")]
    workspace_instance_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    repository_ref: HandoffReportRepositoryRef
    state: State
    confirmed_at: AwareDatetime
    version: Annotated[StrictInt, Field(ge=1)]


class GetHandoffReportWorkspaceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspace_instance_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]


class AttachHandoffReportWorkspaceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspace_instance_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    repository_ref: HandoffReportRepositoryRef
    expected_version: Annotated[StrictInt | None, Field(ge=1)]


class DetachHandoffReportWorkspaceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspace_instance_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    expected_version: Annotated[StrictInt, Field(ge=1)]


class Schema5(StrEnum):
    POWERCONTEXT_PROJECT_V1 = "powercontext.project.v1"


class Schema6(StrEnum):
    POWERCONTEXT_WORKSTREAM_V1 = "powercontext.workstream.v1"


class Kind3(StrEnum):
    ISSUE = "issue"
    TASK = "task"
    PULL_REQUEST = "pull_request"
    BRANCH = "branch"
    FEATURE = "feature"
    RELEASE = "release"
    PROGRAM = "program"
    OTHER = "other"


class HandoffReportExternalReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind3
    provider: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    external_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    url: Annotated[StrictStr | None, Field(max_length=2048)]


class ReportLocale(StrEnum):
    ZH_CN = "zh-CN"
    EN = "en"


class ReportFormat(StrEnum):
    JSON = "json"
    MARKDOWN = "markdown"


class ReportCatalogState(StrEnum):
    INCLUDED = "included"
    ARCHIVED = "archived"


class WorkstreamKind(StrEnum):
    FEATURE = "feature"
    BUG = "bug"
    REFACTOR = "refactor"
    OPERATIONS = "operations"
    RESEARCH = "research"
    OTHER = "other"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: StrictStr


class ListMemoryChangesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    since_revision: Annotated[
        StrictInt | None,
        Field(
            description="Exclusive lower bound; 0 requests complete history from Revision 1. Positive nonexistent revisions are errors.",
            ge=0,
        ),
    ] = None


class ListMemoryEntriesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    include_inactive: Annotated[
        StrictBool, Field(description="Include inactive entries from the current Memory head for explicit audit.")
    ] = False


class ListExternalSkillsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    include_unavailable: StrictBool = False


class MemoryCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory_ref: ArtifactReference
    entry_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    entry_version_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class PrepareContextRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    query: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    max_bytes: Annotated[StrictInt, Field(ge=512, le=32768)] = 8000


class SkillGenerationOrigin(StrEnum):
    EXPERIENCE = "experience"
    SOURCE = "source"
    USAGE = "usage"


class GeneratedCandidateStatus(StrEnum):
    PENDING = "pending"
    NO_OP = "no_op"


class ReadinessStatus(StrEnum):
    READY = "ready"
    DEGRADED = "degraded"
    NOT_READY = "not_ready"


class RememberMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    text: Annotated[StrictStr, Field(description="Must not exceed 8192 UTF-8 bytes after normalization.", min_length=1)]
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None
    expected_revision: Annotated[StrictInt | None, Field(ge=1)] = None


class RetireMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None


class RejectArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    reason: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]


class ReviseMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    text: Annotated[StrictStr, Field(description="Must not exceed 8192 UTF-8 bytes after normalization.", min_length=1)]
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None


class ScanExternalSkillsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ResolveExternalSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    external_skill_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    fingerprint: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]


class ExternalSkillImportMode(StrEnum):
    IMPORT = "import"
    FORK = "fork"


class ImportExternalSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    external_skill_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    fingerprint: Annotated[
        StrictStr,
        Field(description="Exact package fingerprint captured into Source lineage.", pattern="^[0-9a-f]{64}$"),
    ]
    mode: ExternalSkillImportMode
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None


class SourceReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(description="Stable Source type.")]
    source_id: StrictStr


class CaptureStatus(StrEnum):
    ACCEPTED = "accepted"


class StatsPeriod(StrEnum):
    TODAY = "today"
    FIELD_7D = "7d"
    FIELD_30D = "30d"


class CandidateFamily(StrEnum):
    EXPERIENCE = "experience"
    SKILL = "skill"


class ExternalSkillInstallationScope(StrEnum):
    USER = "user"
    PROJECT = "project"
    PLUGIN = "plugin"


class ExternalSkillResolutionStatus(StrEnum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"


class CandidateStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class PreparedContextSchema(StrEnum):
    POWERCONTEXT_PREPARED_CONTEXT_V1 = "powercontext.prepared-context.v1"


class PreparedContextStatus(StrEnum):
    READY = "ready"
    EMPTY = "empty"


class EntryChangeOperation(StrEnum):
    ADD = "add"
    REVISE = "revise"
    DEACTIVATE = "deactivate"
    REACTIVATE = "reactivate"


class FlushStatus(StrEnum):
    IDLE = "idle"
    PROCESSED = "processed"


class MemoryEntryState(StrEnum):
    ACTIVE = "active"
    INACTIVE = "inactive"


class MemoryMatchedBy(StrEnum):
    FTS = "fts"
    VECTOR = "vector"


class MemorySearchMode(StrEnum):
    AUTO = "auto"
    FTS = "fts"
    VECTOR = "vector"
    HYBRID = "hybrid"


class MemoryUsedSearchMode(StrEnum):
    FTS = "fts"
    VECTOR = "vector"
    HYBRID = "hybrid"


class HandoffClaim(StrEnum):
    STATE = "state"
    NEXT_ACTION = "next_action"


class HandoffActivationStatus(StrEnum):
    GENERATED = "generated"
    IGNORED = "ignored"


class HandoffDisposition(StrEnum):
    CONTINUABLE = "continuable"
    BLOCKED = "blocked"
    COMPLETE = "complete"


class HandoffEvidenceStatus(StrEnum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"


class HandoffResolutionStatus(StrEnum):
    EMPTY = "empty"
    RESOLVED = "resolved"


class HandoffSchema(StrEnum):
    POWERCONTEXT_HANDOFF_V1 = "powercontext.handoff.v1"


class HandoffSelection(StrEnum):
    PREPARED = "prepared"
    EXACT = "exact"
    LATEST = "latest"


class PreparedHandoffSchema(StrEnum):
    POWERCONTEXT_PREPARED_HANDOFF_V1 = "powercontext.prepared-handoff.v1"


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_types: list[StrictStr]
    artifact_families: list[StrictStr]
    memory_extraction: Annotated[StrictBool, Field(description="Whether pending Sources can be extracted into Memory.")]
    experience_generation: Annotated[
        StrictBool, Field(description="Whether the configured model can generate reviewed Experience Candidates.")
    ] = False
    managed_skill_generation: Annotated[
        StrictBool, Field(description="Whether the configured model can generate reviewed managed Skill Candidates.")
    ] = False
    external_skill_registry: Annotated[
        StrictBool,
        Field(description="Whether host-local external Skill discovery and exact resolution are configured."),
    ] = False
    handoff_generation: Annotated[
        StrictBool, Field(description="Whether exact evidence can be generated into an inspectable Handoff Draft.")
    ]
    search_modes: list[MemorySearchMode]
    context_versions: list[PreparedContextSchema]


class CandidateFamilyCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: CandidateFamily
    total: Annotated[StrictInt, Field(ge=0)]
    pending: Annotated[StrictInt, Field(ge=0)]
    approved: Annotated[StrictInt, Field(ge=0)]
    rejected: Annotated[StrictInt, Field(ge=0)]


class CandidateInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    pending: Annotated[StrictInt, Field(ge=0)]
    approved: Annotated[StrictInt, Field(ge=0)]
    rejected: Annotated[StrictInt, Field(ge=0)]
    by_family: list[CandidateFamilyCount]


class InventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sources: SourceInventoryStatistics
    artifacts: ArtifactInventoryStatistics
    candidates: CandidateInventoryStatistics
    memory: MemoryInventoryStatistics


class ResolvedUsagePeriod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    preset: StatsPeriod
    start_date: date_aliased
    end_date: date_aliased
    timezone: Timezone


class UsageStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    period: ResolvedUsagePeriod
    totals: ModelUsageStatistics
    by_purpose: Annotated[list[ModelUsagePurposeBreakdown], Field(max_length=16)]
    daily: Annotated[list[ModelUsageDay], Field(max_length=30)]


class RecallTokenStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    period: ResolvedUsagePeriod
    estimator: Annotated[TokenEstimatorProfile | None, Field(...)]
    totals: RecallTokenValue
    daily: Annotated[list[RecallTokenDay], Field(max_length=30)]


class ScopedStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: StrictStr
    as_of: AwareDatetime
    inventory: InventoryStatistics
    usage: UsageStatistics
    recall: RecallTokenStatistics


class GetStatsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    period: StatsPeriod = StatsPeriod.FIELD_30D


class WorkSourceReceipt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: WorkSourceKind
    source: SourceReference
    position: Annotated[StrictInt, Field(ge=1)]
    content_digest: Annotated[StrictStr, Field(max_length=71, min_length=71, pattern="^sha256:[0-9a-f]{64}$")]


class CaptureContentSourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: CaptureStatus
    source: SourceReference
    position: Annotated[StrictInt, Field(ge=1)]


class HandoffMemoryCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["memory"]
    memory_citation: MemoryCitation


class HandoffSourceCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["source"]
    source_ref: SourceReference


class PreparedContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[PreparedContextSchema, Field(alias="schema")]
    status: PreparedContextStatus
    content: Annotated[StrictStr | None, Field(...)]
    content_bytes: Annotated[StrictInt, Field(ge=0)]


class EntryChange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: EntryChangeOperation
    entry_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    from_entry_version_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    to_entry_version_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    reason: Annotated[StrictStr | None, Field(...)]


class ExperienceArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    content: ExperienceProposal
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class SkillProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    description: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    instructions: Annotated[StrictStr, Field(max_length=32000, min_length=1, pattern=".*\\S.*")]
    validation: Annotated[list[SkillValidationItem], Field(max_length=32, min_length=1)]


class ExternalSkillRegistration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    external_skill_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    provider: Provider
    agent_kind: AgentKind
    host_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    installation_scope: ExternalSkillInstallationScope
    locator: Annotated[
        StrictStr,
        Field(
            description="Host-local locator; not a cross-Agent or cross-host contract.",
            max_length=2000,
            min_length=1,
            pattern="^\\S(?:.*\\S)?$",
        ),
    ]
    fingerprint: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    description: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern="^\\S(?:.*\\S)?$")]


class ExternalSkillResolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    registration: ExternalSkillRegistration
    status: ExternalSkillResolutionStatus
    entrypoint: Annotated[
        StrictStr | None,
        Field(description="Host-local SKILL.md path; present only when the exact fingerprint is available."),
    ]


class ScanExternalSkillsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    registrations: list[ExternalSkillRegistration]
    skipped: Annotated[StrictInt, Field(ge=0)]


class ListExternalSkillsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skills: list[ExternalSkillResolution]


class FlushMemoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: FlushStatus
    previous_cursor: Annotated[StrictInt, Field(ge=0)]
    current_cursor: Annotated[StrictInt, Field(ge=0)]
    high_watermark: Annotated[StrictInt, Field(ge=0)]
    processed_source_count: Annotated[StrictInt, Field(ge=0)]
    memory: ArtifactReference | None = None


class GetMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation


class CreateHandoffReportProjectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_key: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    description: Annotated[StrictStr | None, Field(max_length=2000)] = None
    default_locale: ReportLocale = ReportLocale.ZH_CN
    timezone: Annotated[StrictStr, Field(max_length=256, min_length=1)] = "UTC"


class RegisterHandoffReportWorkstreamRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    key: Annotated[StrictStr | None, Field(max_length=64, min_length=1)] = None
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    kind: WorkstreamKind
    catalog_state: ReportCatalogState = ReportCatalogState.INCLUDED
    external_refs: Annotated[list[HandoffReportExternalReference], Field(max_length=32, validate_default=True)] = []
    labels: Annotated[list[Label], Field(max_length=32, validate_default=True)] = []


class GetHandoffReportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    project_id: Annotated[
        StrictStr | None,
        Field(
            deprecated=True,
            description="Retained for wire compatibility and ignored when generating a scope report.",
            max_length=256,
            min_length=1,
        ),
    ] = None
    locale: ReportLocale | None = None
    include_evidence_checks: StrictBool = True
    format: ReportFormat = ReportFormat.MARKDOWN
    include_archived: StrictBool = False
    download: StrictBool = False
    period: HandoffReportPeriodRequest | None = None


class HandoffReportResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: ReportFormat
    report: Annotated[dict[str, Any] | None, Field(...)]
    markdown: Annotated[StrictStr | None, Field(...)]
    selection_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]
    report_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]


class RecordHandoffReportActivityRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1)] = None
    source: ReportActivitySource
    source_event_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    source_ref: HandoffReportExternalReference | None = None
    occurred_at: AwareDatetime | None = None
    time_basis: ReportTimeBasis
    title: Annotated[StrictStr | None, Field(max_length=256, min_length=1)] = None
    summary: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None
    agent: HandoffReportActivityAgent | None = None
    session_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1)] = None
    vcs_context: HandoffReportActivityVcsContext | None = None
    evidence_refs: Annotated[list[HandoffReportExternalReference], Field(max_length=32, validate_default=True)] = []


class HandoffReportActivity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema3, Field(alias="schema")]
    event_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1)]
    source: ReportActivitySource
    source_event_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    source_ref: Annotated[HandoffReportExternalReference | None, Field(...)]
    occurred_at: Annotated[AwareDatetime | None, Field(...)]
    observed_at: AwareDatetime
    time_basis: ReportTimeBasis
    title: Annotated[StrictStr | None, Field(max_length=256, min_length=1)]
    summary: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)]
    agent: Annotated[HandoffReportActivityAgent | None, Field(...)]
    session_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1)]
    vcs_context: Annotated[HandoffReportActivityVcsContext | None, Field(...)]
    evidence_refs: Annotated[list[HandoffReportExternalReference], Field(max_length=32)]
    trust: Trust4


class StoredHandoffReportActivity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: Annotated[StrictInt, Field(ge=1)]
    event: HandoffReportActivity


class HandoffReportActivityPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[HandoffReportActivity], Field(max_length=100)]
    next_cursor: Annotated[StrictInt | None, Field(ge=1)]
    high_watermark: Annotated[StrictInt, Field(ge=0)]


class ProjectDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema5, Field(alias="schema")]
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    project_key: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    description: Annotated[StrictStr | None, Field(max_length=2000)]
    default_locale: ReportLocale
    timezone: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    catalog_state: ReportCatalogState
    version: Annotated[StrictInt, Field(ge=1)]


class ProjectPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[ProjectDescriptor], Field(max_length=100)]
    next_cursor: Annotated[StrictStr | None, Field(...)]


class WorkstreamDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema6, Field(alias="schema")]
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    project_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    key: Annotated[StrictStr | None, Field(max_length=64)]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    kind: WorkstreamKind
    catalog_state: ReportCatalogState
    external_refs: Annotated[list[HandoffReportExternalReference], Field(max_length=32)]
    labels: Annotated[list[Label], Field(max_length=32)]
    version: Annotated[StrictInt, Field(ge=1)]


class WorkstreamPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[WorkstreamDescriptor], Field(max_length=100)]
    next_cursor: Annotated[StrictStr | None, Field(...)]


class ListArtifactCandidatesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    status: CandidateStatus = CandidateStatus.PENDING
    family: CandidateFamily | None = None
    cursor: Annotated[StrictStr | None, Field(max_length=128, min_length=1)] = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50


class MemoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    citation: MemoryCitation
    version: Annotated[StrictInt, Field(ge=1)]
    kind: StrictStr
    text: StrictStr
    state: MemoryEntryState
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class MemoryMutationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference
    entry: MemoryEntry | None = None


class MemoryRevisionChanges(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory_ref: ArtifactReference
    changes: list[EntryChange]


class ProposeExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    proposal: ExperienceProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class GenerateExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ProposeSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    proposal: SkillProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class GenerateSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    origin: SkillGenerationOrigin
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ReadinessResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: ReadinessStatus
    checks: dict[str, StrictStr]


class ReviseArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    proposal: ExperienceProposal | SkillProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class SearchMemoryHit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    citation: MemoryCitation
    text: StrictStr
    score: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    matched_by: list[MemoryMatchedBy]


class SearchMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    query: Annotated[StrictStr, Field(max_length=8192, min_length=1)]
    limit: Annotated[StrictInt, Field(ge=1, le=50)] = 10
    mode: MemorySearchMode = MemorySearchMode.AUTO


class SearchMemoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    mode: MemoryUsedSearchMode | None = None
    hits: list[SearchMemoryHit]


class ArtifactCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    version: Annotated[StrictInt, Field(ge=1)]
    family: CandidateFamily
    status: CandidateStatus
    proposal: ExperienceProposal | SkillProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: Annotated[ArtifactReference | None, Field(...)]
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)]
    result_artifact: Annotated[ArtifactReference | None, Field(...)]
    decision_reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)]

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ArtifactCandidatePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: list[ArtifactCandidate]
    next_cursor: Annotated[StrictStr | None, Field(...)]


class HandoffCitation(RootModel[HandoffSourceCitation | HandoffArtifactCitation | HandoffMemoryCitation]):
    root: Annotated[
        HandoffSourceCitation | HandoffArtifactCitation | HandoffMemoryCitation, Field(discriminator="kind")
    ]


class HandoffEvidenceCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim: HandoffClaim
    state_index: Annotated[StrictInt | None, Field(ge=0)]
    status: HandoffEvidenceStatus
    unavailable_evidence: Annotated[list[HandoffCitation], Field(max_length=32)]


class HandoffOmission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    citation: Annotated[HandoffCitation | None, Field(...)]


class HandoffStatement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    citations: Annotated[list[HandoffCitation], Field(max_length=32, min_length=1)]


class PrepareHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    evidence: Annotated[list[HandoffCitation], Field(max_length=32, min_length=1)]
    max_bytes: Annotated[StrictInt, Field(ge=512, le=32768)] = 8000


class SkillArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    content: SkillProposal
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class UpdateHandoffReportProjectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project: ProjectDescriptor
    expected_version: Annotated[StrictInt, Field(ge=1)]


class UpdateHandoffReportWorkstreamRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workstream: WorkstreamDescriptor
    expected_version: Annotated[StrictInt, Field(ge=1)]


class ListMemoryChangesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    revisions: list[MemoryRevisionChanges]


class ListMemoryEntriesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    entries: list[MemoryEntry]


class GeneratedCandidateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: GeneratedCandidateStatus
    candidate: Annotated[ArtifactCandidate | None, Field(...)]


class ActivateHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    boundary_source: SourceReference
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    evidence: Annotated[list[HandoffCitation], Field(max_length=32, validate_default=True)] = []
    max_bytes: Annotated[StrictInt, Field(ge=512, le=32768)] = 8000


class WorkClaim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    basis: WorkClaimBasis
    evidence: Annotated[list[HandoffCitation], Field(max_length=31)]


class WorkContract(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema, Field(alias="schema")]
    trust: Trust
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    facts: Annotated[list[WorkClaim], Field(max_length=64)]
    in_scope: Annotated[list[InScopeItem], Field(max_length=64, min_length=1)]
    exclusions: Annotated[list[Exclusion], Field(max_length=64)]
    completion_criteria: Annotated[list[CompletionCriterion], Field(max_length=64, min_length=1)]
    authorization_notes: Annotated[list[AuthorizationNote], Field(max_length=64)]
    open_questions: Annotated[list[OpenQuestion], Field(max_length=64)]


class CreateWorkContractRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    contract: WorkContract


class CurrentWorkHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema1, Field(alias="schema")]
    trust: Trust
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    state: Annotated[list[WorkClaim], Field(max_length=64, min_length=1)]
    disposition: HandoffDisposition
    next_action: Annotated[WorkClaim | None, Field(...)]
    omissions: Annotated[list[Omission], Field(max_length=64)]


class HandoffCurrentWorkRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    handoff: CurrentWorkHandoff


class TaskCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    status: TaskCheckStatus
    details: Annotated[StrictStr | None, Field(max_length=8192, min_length=1, pattern=".*\\S.*")] = None
    basis: WorkClaimBasis
    evidence: Annotated[list[HandoffCitation], Field(max_length=32)]


class TaskOutcome(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema2, Field(alias="schema")]
    trust: Trust2
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    status: TaskOutcomeStatus
    summary: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    handoff_receipt_ref: SourceReference | None = None
    observations: Annotated[list[WorkClaim], Field(max_length=64, min_length=1)]
    checks: Annotated[list[TaskCheck], Field(max_length=64)]
    produced_artifacts: Annotated[list[ArtifactReference], Field(max_length=32)]
    remaining_work: Annotated[list[RemainingWorkItem], Field(max_length=64)]


class RecordTaskOutcomeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    outcome: TaskOutcome


class HandoffContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[HandoffSchema, Field(alias="schema")]
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    state: Annotated[list[HandoffStatement], Field(max_length=64, min_length=1)]
    disposition: HandoffDisposition
    next_action: Annotated[HandoffStatement | None, Field(...)]
    omissions: Annotated[list[HandoffOmission], Field(max_length=64)]


class HandoffDraft(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    state: Annotated[list[HandoffStatement], Field(max_length=64, min_length=1)]
    disposition: HandoffDisposition
    next_action: Annotated[HandoffStatement | None, Field(...)]
    omissions: Annotated[list[HandoffOmission], Field(max_length=64)]


class HandoffResolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trust: Trust3
    status: HandoffResolutionStatus
    scope_id: StrictStr
    content: Annotated[HandoffContent | None, Field(...)]
    selection: Annotated[HandoffSelection | None, Field(...)]
    selected_revision: Annotated[ArtifactReference | None, Field(...)]
    current_revision: Annotated[ArtifactReference | None, Field(...)]
    evidence_checks: Annotated[list[HandoffEvidenceCheck], Field(max_length=65)]


class PreparedHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[PreparedHandoffSchema, Field(alias="schema")]
    scope_id: StrictStr
    base: Annotated[ArtifactReference | None, Field(...)]
    content: HandoffContent


class PreparedWorkHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    boundary: WorkSourceReceipt
    handoff: PreparedHandoff


class AcknowledgeHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    receiver: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    status: HandoffReceiptStatus
    selection: HandoffAcknowledgementSelection
    receiver_checks: ReceiverChecks | None = None
    prepared: PreparedHandoff | None = None
    revision: ArtifactReference | None = None
    message: Annotated[StrictStr | None, Field(max_length=8192, min_length=1, pattern=".*\\S.*")] = None


class HandoffAcknowledgement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolution: HandoffResolution
    receipt: WorkSourceReceipt


class CommitHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    handoff: PreparedHandoff


class CommittedHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reference: ArtifactReference
    content: HandoffContent
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class ContinueHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    selection: HandoffSelection
    prepared: PreparedHandoff | None = None
    revision: ArtifactReference | None = None


class FinalizeHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    draft: HandoffDraft


class HandoffActivation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: HandoffActivationStatus
    boundary_source: SourceReference
    previous_position: Annotated[StrictInt, Field(ge=0)]
    current_position: Annotated[StrictInt, Field(ge=0)]
    draft: Annotated[HandoffDraft | None, Field(...)]
